### ISSUE TITLE
Make ProtocolFlx thread safe

### ISSUE THREAD

**Issue by jimbrooke** [DUNE-DAQ/uhallibs#4]
In order to add monitoring functionality for DUNE FW TPs (https://github.com/DUNE-DAQ/dtpctrllibs/issues/6) some protection of the common control bus will be needed from accesses on multiple threads.  It seems sensible to put that protection around ProtocolFlx than in DTPController.  Can use ProtocolAxi4Lite as a template.

**Comment by alessandrothea** [comment]
Closed by  PR #6
